global using CommunityToolkit.Maui;
global using CommunityToolkit.Maui.Alerts;
global using CommunityToolkit.Maui.ApplicationModel;
global using CommunityToolkit.Maui.Core;
global using CommunityToolkit.Maui.Core.Extensions;
global using CommunityToolkit.Maui.Views;
global using CommunityToolkit.Mvvm.Messaging;
global using Plugin.Maui.Audio;
global using Plugin.Maui.Biometric;
global using ReactiveUI;
global using ReactiveUI.Fody.Helpers;
global using ReactiveUI.Maui;
global using SkiaSharp.Views.Maui.Controls.Hosting;
global using System.Collections.ObjectModel;
global using System.ComponentModel;
global using System.Globalization;
global using System.Net;
global using System.Reactive;
global using System.Reactive.Disposables;
global using System.Reactive.Linq;
global using System.Timers;
global using UraniumUI;
global using VisitTracker.Domain;
global using VisitTracker.Services;
global using VisitTracker.Shared;
global using ZXing.Net.Maui;
global using ZXing.Net.Maui.Controls;
global using Constants = VisitTracker.Shared.Constants;
global using INotificationService = VisitTracker.Services.INotificationService;
global using NotificationService = VisitTracker.Services.NotificationService;
global using Timer = System.Timers.Timer;